version: '3'
services:
  php-app:
    build: .
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
  react-app:
    build:
      context: ./react
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
